### PR TITLE
Addding ssh-ed25519 key for GHTorrent. I hope it works

### PR DESCRIPTION
**Pull request by timofonic**
I would like to work on GHTorrent data for research purposes, initially doing some small research experiments on digital preservation:

- I often find interesting apps and despite the binary and sometimes the tarball are avaiable somewhere, the GitHub repo has disappeared or there's one without the Git history.

I also want to use it as a last resource mirror of my own public projects, just in case they get deleted accidentally.

 It would be amazing if you can add my key, I gave a ssh-ed25519 just for the sake of it, I hope your systems are compatible with non-rsa keys.

Thank you!

### CODE REVIEW

**Comment by timofonic** [comment]
@gousiosg Any news?

**Comment by gousiosg** [comment]
Pull requests have been restored, repos are currently being restored.

**Comment by timofonic** [comment]
@gousiosg Excuse me...
What do you mean?

**Comment by gousiosg** [comment]
Sorry, this comment was meant for another thread... :-)

**Pull request merged**
